### ISSUE TITLE
Versions below 1.0.0 are not available

### ISSUE THREAD

**Issue by jfwm2** [aerospike/aerospike-kubernetes-init#8]
Hello
I cannot find version 0.0.12 of https://github.com/aerospike/aerospike-kubernetes-init; this version is the one use in the operator (see https://github.com/aerospike/aerospike-kubernetes-operator/blob/master/pkg/controller/aerospikecluster/controller_helper.go#L122) and it does not seems to work with versions not less than 1.0.0, which are the only ones present of the current repository.
Could you please give me access to the missing versions (at least 0.0.12)?
Thanks
Jean-Francois

**Comment by spkesan** [comment]
@jfwm2 This repo is contains init container used in our "generic" Helm Charts,
- https://artifacthub.io/packages/helm/aerospike/aerospike
- https://artifacthub.io/packages/helm/aerospike/aerospike-enterprise

I'll close this issue and provide a response in the operator repo.

**Comment by jfwm2** [comment]
Thanks @spkesan!!
